-- 1. posts (게시글 테이블) 생성
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  author_email text,
  views integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. post_likes (좋아요 테이블) 생성
CREATE TABLE IF NOT EXISTS public.post_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(post_id, user_id)
);

-- 3. Row Level Security (RLS) 활성화
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;

-- 4. posts 테이블 RLS 정책 설정
-- 4-1. 누구나 게시글을 조회할 수 있음
CREATE POLICY "Allow public select on posts" 
ON public.posts 
FOR SELECT 
USING (true);

-- 4-2. 로그인한 사용자만 본인 id로 게시글을 생성할 수 있음
CREATE POLICY "Allow authenticated insert on posts" 
ON public.posts 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = author_id);

-- 4-3. 본인 게시글만 수정할 수 있음
CREATE POLICY "Allow author update on posts" 
ON public.posts 
FOR UPDATE 
TO authenticated 
USING (auth.uid() = author_id)
WITH CHECK (auth.uid() = author_id);

-- 4-4. 본인 게시글만 삭제할 수 있음
CREATE POLICY "Allow author delete on posts" 
ON public.posts 
FOR DELETE 
TO authenticated 
USING (auth.uid() = author_id);

-- 5. post_likes 테이블 RLS 정책 설정
-- 5-1. 누구나 좋아요 정보를 조회할 수 있음 (좋아요 카운트 집계를 위해 필요)
CREATE POLICY "Allow public select on post_likes" 
ON public.post_likes 
FOR SELECT 
USING (true);

-- 5-2. 로그인한 사용자만 본인 user_id로 좋아요를 추가할 수 있음
CREATE POLICY "Allow authenticated insert on post_likes" 
ON public.post_likes 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- 5-3. 로그인한 사용자만 본인 user_id의 좋아요를 취소(삭제)할 수 있음
CREATE POLICY "Allow authenticated delete on post_likes" 
ON public.post_likes 
FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- 6. 조회수 증가용 SECURITY DEFINER 함수 생성 (RLS 우회 목적)
CREATE OR REPLACE FUNCTION public.increment_views(post_id bigint)
RETURNS void AS $$
BEGIN
  UPDATE public.posts
  SET views = views + 1
  WHERE id = post_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

